In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [3]:
suma = A + B
print("Suma de matrices:\n", suma)

Suma de matrices:
 [[ 6  8]
 [10 12]]


In [4]:
producto = np.dot(A, B)
print("Producto de matrices:\n", producto)

Producto de matrices:
 [[19 22]
 [43 50]]


In [5]:
#Código en NumPy para el determinante de una matriz:

In [6]:
determinante = np.linalg.det(A)
print("Determinante de A:", determinante)

Determinante de A: -2.0000000000000004


In [ ]:
#La matriz inversa de A

In [7]:
inversa = np.linalg.inv(A)
print("Inversa de A:\n", inversa)

Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#Los valores propios y los vectores propios son fundamentales en muchas aplicaciones, como en la compresión de datos y el análisis de sistemas dinámicos.

In [8]:
valores_propios, vectores_propios = np.linalg.eig(A)
print("Valores propios de A:\n", valores_propios)
print("Vectores propios de A:\n", vectores_propios)

Valores propios de A:
 [-0.37228132  5.37228132]
Vectores propios de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [9]:
#Para resolver un sistema de ecuaciones lineales AX=BAX = BAX=B:

In [10]:
B = np.array([1, 2])
X = np.linalg.solve(A, B)
print("Solución del sistema AX = B:\n", X)

Solución del sistema AX = B:
 [0.  0.5]
