In [1]:
#Importar Numpy
import numpy as np


In [2]:
meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])
ventas_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
ventas_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
ventas_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])


In [3]:
# Producto A
media_A = np.mean(ventas_A)
suma_A = np.sum(ventas_A)

# Producto B
media_B = np.mean(ventas_B)
suma_B = np.sum(ventas_B)

# Producto C
media_C = np.mean(ventas_C)
suma_C = np.sum(ventas_C)

# Imprimir
print(f"Media de ventas Producto A: {media_A}")
print(f"Suma de ventas Producto A: {suma_A}\n")

print(f"Media de ventas Producto B: {media_B}")
print(f"Suma de ventas Producto B: {suma_B}\n")

print(f"Media de ventas Producto C: {media_C}")
print(f"Suma de ventas Producto C: {suma_C}")


Media de ventas Producto A: 229.16666666666666
Suma de ventas Producto A: 2750

Media de ventas Producto B: 257.5
Suma de ventas Producto B: 3090

Media de ventas Producto C: 310.0
Suma de ventas Producto C: 3720


In [6]:
total_ventas_mes = ventas_A + ventas_B + ventas_C
print(f"Total de ventas por mes:\n{total_ventas_mes}")


Total de ventas por mes:
[ 530  630  720  810  770  770  740  780  860  910  990 1050]


In [7]:
mes_max = meses[np.argmax(total_ventas_mes)]
mes_min = meses[np.argmin(total_ventas_mes)]

print(f"Mes con mayores ventas: {mes_max}")
print(f"Mes con menores ventas: {mes_min}")


Mes con mayores ventas: Diciembre
Mes con menores ventas: Enero


In [8]:
ventas = np.array([ventas_A, ventas_B, ventas_C])
print("Matriz de ventas 2D:")
print(ventas)


Matriz de ventas 2D:
[[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]


In [9]:
ventas_reshape = ventas.reshape(3, 4, 3)
print("\nMatriz reshaped (3, 4, 3):")
print(ventas_reshape)



Matriz reshaped (3, 4, 3):
[[[150 200 250]
  [300 220 210]
  [180 190 230]
  [240 280 300]]

 [[180 210 230]
  [250 270 260]
  [240 250 270]
  [290 310 330]]

 [[200 220 240]
  [260 280 300]
  [320 340 360]
  [380 400 420]]]


In [10]:
ventas_transpuesta = ventas.T
print("\nMatriz transpuesta:")
print(ventas_transpuesta)



Matriz transpuesta:
[[150 180 200]
 [200 210 220]
 [250 230 240]
 [300 250 260]
 [220 270 280]
 [210 260 300]
 [180 240 320]
 [190 250 340]
 [230 270 360]
 [240 290 380]
 [280 310 400]
 [300 330 420]]


In [11]:
ventas_A_invertida = ventas_A[::-1]
ventas_B_invertida = ventas_B[::-1]
ventas_C_invertida = ventas_C[::-1]

print("\nVentas A invertida:")
print(ventas_A_invertida)



Ventas A invertida:
[300 280 240 230 190 180 210 220 300 250 200 150]


In [12]:
ventas_flatten = ventas.flatten()
print("\nVentas aplanadas:")
print(ventas_flatten)



Ventas aplanadas:
[150 200 250 300 220 210 180 190 230 240 280 300 180 210 230 250 270 260
 240 250 270 290 310 330 200 220 240 260 280 300 320 340 360 380 400 420]


In [13]:
# Encontrar elementos únicos en las ventas combinadas
elementos_unicos, conteos = np.unique(ventas_flatten, return_counts=True)

print("\nElementos únicos:")
print(elementos_unicos)

print("\nConteo de cada elemento único:")
print(conteos)



Elementos únicos:
[150 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340
 360 380 400 420]

Conteo de cada elemento único:
[1 2 1 2 2 2 2 3 3 2 2 2 1 3 1 1 1 1 1 1 1 1]


In [14]:
ventas_primer_trimestre = ventas[:, :3]
print("\nVentas primer trimestre:")
print(ventas_primer_trimestre)



Ventas primer trimestre:
[[150 200 250]
 [180 210 230]
 [200 220 240]]


In [15]:
meses_mas_800 = meses[total_ventas_mes > 800]
ventas_mas_800 = total_ventas_mes[total_ventas_mes > 800]

print("\nMeses con ventas > 800:")
for mes, venta in zip(meses_mas_800, ventas_mas_800):
    print(f"{mes}: {venta}")



Meses con ventas > 800:
Abril: 810
Septiembre: 860
Octubre: 910
Noviembre: 990
Diciembre: 1050


In [16]:
# Índices de meses pares (considerando que 0 = Enero)
indices_pares = [1, 3, 5, 7, 9, 11]

ventas_meses_pares = ventas[:, indices_pares]
print("\nVentas en meses pares:")
print(ventas_meses_pares)



Ventas en meses pares:
[[200 300 210 190 240 300]
 [210 250 260 250 290 330]
 [220 260 300 340 380 420]]
