In [2]:
import numpy as np


In [3]:
escalar=np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [4]:
vector=np.array([10,28,30,45,52,42])
print((vector))

[10 28 30 45 52 42]


In [5]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
tensor=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(tensor)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
array_arange=np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
eye_matrix=np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
diag=np.diag([1,2,3,4,5,6,7,8,9])
print(diag)

[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]


In [15]:
random=np.random.random((2,3))
print(random)

[[0.48886111 0.01758461 0.2692816 ]
 [0.89146775 0.63751832 0.61869021]]
