## Que es Brodcasting

Broadcasting es una forma que tiene NumPy de aplicar operaciones matemáticas entre arrays de diferentes formas o tamaños, siempre que sus dimensiones sean compatibles.

🧠 Imagina esto:
Quieres sumar un número a cada elemento de una lista. En lugar de usar un bucle for, NumPy lo hace de forma automática gracias al broadcasting

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = 10

In [3]:
resultado = a + b  # Broadcasting automático
print(resultado)   # [11 12 13]

[11 12 13]


🔎 NumPy "extiende" automáticamente b para que actúe como [10, 10, 10].

✅ Ejemplo 2: Sumar un vector a una matriz (fila por fila)

In [4]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([10, 20, 30])

resultado = a + b
print(resultado)

[[11 22 33]
 [14 25 36]]


 ##  🔹¿Qué son las Operaciones Lógicas en NumPy?

 Las operaciones lógicas en NumPy se usan para comparar arrays y generar máscaras booleanas (**True** o **False**), útiles para filtrar datos.

✅ Ejemplo 3: Comparar todos los elementos de un array

In [8]:
a = np.array([1, 2, 3, 4, 5])

mayores_que_dos = a > 2
print(mayores_que_dos)  # [False False  True  True  True]


[False False  True  True  True]


✅ Ejemplo 4: Filtrar con condiciones

In [9]:
resultado = a[a > 2]
print(resultado)  # [3 4 5]


[3 4 5]


🔎 Esto es muy útil para trabajar con datasets o resultados numéricos.

✅ Ejemplo 5: Usar múltiples condiciones lógicas

In [10]:
a = np.array([10, 15, 20, 25, 30])

# Seleccionar valores entre 15 y 25
filtro = (a >= 15) & (a <= 25)
print(a[filtro])  # [15 20 25]


[15 20 25]


⚠️ Importante: En NumPy, debes usar &, |, ~ en vez de and, or, not.