🧪 Ejercicios de Broadcasting

✅ Ejercicio 1: Sumar un escalar a un arr

In [1]:
import numpy as np

In [3]:
# Crea un array del 1 al 5
a = np.array([1, 2, 3, 4, 5])
#Sumarle 100 a todos los elementos del array
b=100
resultado= a+b
print(resultado)

[101 102 103 104 105]


✅ Ejercicio 2: Multiplicar una matriz por un vector

In [7]:
# Crea una matriz de 3x3
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Crea un vector: [10, 20, 30]
vector = np.array([10, 20, 30])

# Usa broadcasting para multiplicar cada fila por el vector
resultado= matriz * vector
print(resultado)

[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


✅ Ejercicio 3: Restar un vector a una matriz (por columnas)

In [19]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
vector_col = np.array([1, 2, 3]).reshape(3, 1)
resultado = matriz - vector_col
print(resultado)



[[0 1 2]
 [2 3 4]
 [4 5 6]]


🔍 Ejercicios de Operaciones Lógicas

✅ Ejercicio 4: Filtro básico

In [10]:
# Crea un array con los números del 1 al 10
x = np.arange(1, 11)
resultado= x[x>5]
print(resultado)

[ 6  7  8  9 10]


✅ Ejercicio 5: Doble condición

In [14]:
# Usando el array x anterior
x = np.arange(1, 11)
# Filtra los números que sean pares y mayores que 3
resultado= x[(x % 2 == 0) & (x > 3)]
print(resultado)



[ 4  6  8 10]


✅ Ejercicio 6: Reemplazo condicional

In [18]:
# Crea un array con los números del 1 al 10
x = np.arange(1, 11)

# Verificar si hay al menos un valor mayor que 5
if np.any(x > 5):
    x[x > 5] = 0
else:
    print("No hay números mayores que 5")

print(x)

[1 2 3 4 5 0 0 0 0 0]
