## Indexacion y Slicing

In [3]:
import numpy as np

In [7]:
array=np.array([10,20,30,40,50])
print(array[1])
print(array[-1])

20
50


In [5]:
print(array[1:4])

[20 30 40]


In [6]:
print(array[-1:-7])

[]


In [10]:
array=np.array([10,20,30,40,50])
bool_index=array>25
print(bool_index)
print(type(bool_index))


[False False  True  True  True]
<class 'numpy.ndarray'>


In [11]:
index=[2,3,4]
print(array[index])

[30 40 50]


In [12]:
array=np.random.randint(1,10,size=(3,3))
print(array)
print(array[0,1])

[[7 8 3]
 [2 1 5]
 [9 3 4]]
8


In [13]:
print(array[:2,:2])

[[7 8]
 [2 1]]


# Reto  

## Acceder a elementos específicos  
Crea un arreglo de 10 números y accede al cuarto y penúltimo elemento usando índices positivos y negativos.  

## Slicing de arreglos  
Dado un arreglo de números del 1 al 20, extrae los elementos entre las posiciones 3 y 7, y luego los elementos de las últimas 5 posiciones.  

## Indexing con booleanos  
Crea un arreglo de números aleatorios entre 0 y 100. Usa una expresión booleana para acceder solo a los números mayores a 50.  

## Indexación con múltiples índices  
Dado un arreglo de 8 elementos, crea una lista de índices para acceder a los elementos en las posiciones 1, 4 y 6.  

## Matrices bidimensionales  
Genera una matriz 4x4 de números aleatorios entre 10 y 50, y accede a la submatriz de 2x2 ubicada en la esquina inferior derecha.  
