In [2]:
import numpy as np


In [2]:
mi_array = np.array([1, 2, 3, 4, 5])
print(mi_array)


[1 2 3 4 5]


In [3]:
arrayP = np.arange(10, 51)
print(arrayP)

print(arrayP.size)
print(arrayP.shape)
print(arrayP.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
41
(41,)
int64


### Operaciones

In [8]:
x = np.array([5, 10, 15, 20])

y = np.array([2, 4, 6, 8])

print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**2)


[ 7 14 21 28]
[ 3  6  9 12]
[ 10  40  90 160]
[2.5 2.5 2.5 2.5]
[ 25 100 225 400]


###  Indexación y Slicing en arrays🔪👨‍⚕️

In [1]:
import numpy as np

In [10]:
edades = np.array([15, 22, 18, 30, 25, 40, 17, 19])
print(edades[:4])  # Primeros 4 elementos
print(edades[edades>20])# Elementos mayores a 20
edades[2]=99
print(edades)  # Cambia el tercer elemento a 99
print(edades[[1, 3, 5]])   # Esto selecciona directamente esas posiciones


[15 22 18 30]
[22 30 25 40]
[15 22 99 30 25 40 17 19]
[22 30 40]


### 🧠 EJERCICIO: Indexación y Slicing con Datos de Ventas

In [4]:
import numpy as np

meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])

ventas_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
ventas_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
ventas_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])


In [3]:
print("Ventas de la empresa A primer trimestre:")
meses_A = meses[:3] 
print(meses_A) # Primer trimestre (Enero, Febrero, Marzo)
ventas_A_trimestre = ventas_A[:3] # Ventas de la empresa A en el primer trimestre
print(ventas_A_trimestre)

print("Venta meses pares:")
ventas_meses_pares = ventas_C[1::2] # Ventas de meses pares (Febrero, Abril, Junio, Agosto, Octubre, Diciembre)
print(ventas_meses_pares)
print("total venta mes")
total_venta_mes=ventas_A+ventas_B+ventas_C
print(total_venta_mes) # Total de ventas por mes
print(total_venta_mes[total_venta_mes>800])# Ventas totales mayores a 800
print("ventas producto B ultimos 4 meses")
ventas_B_ultimos_4=ventas_B[-4:]
print(ventas_B_ultimos_4) # Ventas de la empresa B en los últimos 4 meses

Ventas de la empresa A primer trimestre:
['Enero' 'Febrero' 'Marzo']
[150 200 250]
Venta meses pares:
[220 260 300 340 380 420]
total venta mes
[ 530  630  720  810  770  770  740  780  860  910  990 1050]
[ 810  860  910  990 1050]
ventas producto B ultimos 4 meses
[270 290 310 330]


### 1. Calcula la media y suma de ventas de cada producto:

In [7]:
ventas_A.mean()
print(ventas_A.mean()) # Promedio de ventas de la empresa A
print(ventas_A.sum()) # Suma de ventas de la empresa A
print(ventas_B.mean()) # Promedio de ventas de la empresa B
print(ventas_B.sum()) # Suma de ventas de la empresa B
print(ventas_C.mean()) # Promedio de ventas de la empresa C
print(ventas_C.sum()) # Suma de ventas de la empresa C


indice_mayor = total_venta_mes.argmax()
indice_menor = total_venta_mes.argmin()
print("Mes con mayor venta:", meses[indice_mayor]) # Mes con mayor venta
print("Mes con menor venta:", meses[indice_menor]) # Mes con menor venta
mayor_venta_A=ventas_A.max()
indice_mayor_venta_A=ventas_A.argmax()
print("Mayor venta empresa A:", mayor_venta_A) # Mayor venta de la empresa A
print("Mes con mayor venta empresa A:", meses[indice_mayor_venta_A]) # Mes con mayor venta de la empresa A

229.16666666666666
2750
257.5
3090
310.0
3720
Mes con mayor venta: Diciembre
Mes con menor venta: Enero
Mayor venta empresa A: 300
Mes con mayor venta empresa A: Abril


In [10]:
total_venta_anual = total_venta_mes.sum()
print("Total de ventas del año:", total_venta_anual)

print(ventas_B[ventas_B > ventas_B.mean()])
print("Ventas de la empresa B mayores al promedio:", meses[ventas_B > ventas_B.mean()]) # Ventas de la empresa B mayores al promedio


Total de ventas del año: 9560
[270 260 270 290 310 330]
Ventas de la empresa B mayores al promedio: ['Mayo' 'Junio' 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']


### 1. reshape() – Cambiar la forma de un array

In [11]:
import numpy as np

array_original = np.array([1, 2, 3, 4, 5, 6])
array_2d = array_original.reshape((2, 3))
print(array_2d)
# Resultado:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


### 2. transpose() – Transponer una matriz

In [12]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
transpuesta = matriz.T
print(transpuesta)
# Resultado:
# [[1 4]
#  [2 5]
#  [3 6]]


[[1 4]
 [2 5]
 [3 6]]


### 3. flatten() – Aplanar un array multidimensional

In [13]:
matriz = np.array([[1, 2], [3, 4]])
plano = matriz.flatten()
print(plano)
# Resultado: [1 2 3 4]


[1 2 3 4]


### 4. Invertir un array

In [14]:
array = np.array([10, 20, 30])
invertido = array[::-1]
print(invertido)
# Resultado: [30 20 10]


[30 20 10]


🔄 Convierte ventas_A, ventas_B y ventas_C en una sola matriz 2D con reshape() (tamaño 3x12).

In [16]:
union_array=np.concatenate([ventas_A, ventas_B, ventas_C])
#print(union_array) # Unión de los tres arrays de ventas

ventas_2d=union_array.reshape(3, 12)
print(ventas_2d) # Ventas en 2D (3 filas, 12 columnas)

[[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]


In [17]:
transpuesta_ventas=ventas_2d.T
print(transpuesta_ventas) # Transpuesta de la matriz de ventas

[[150 180 200]
 [200 210 220]
 [250 230 240]
 [300 250 260]
 [220 270 280]
 [210 260 300]
 [180 240 320]
 [190 250 340]
 [230 270 360]
 [240 290 380]
 [280 310 400]
 [300 330 420]]


In [18]:
plana=ventas_2d.flatten()
print(plana) # Aplanada la matriz de ventas

[150 200 250 300 220 210 180 190 230 240 280 300 180 210 230 250 270 260
 240 250 270 290 310 330 200 220 240 260 280 300 320 340 360 380 400 420]


In [19]:
invertido=ventas_2d[::-1]
print(invertido) # Invertida la matriz de ventas

[[200 220 240 260 280 300 320 340 360 380 400 420]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [150 200 250 300 220 210 180 190 230 240 280 300]]


In [ ]:
import numpy as np
ventas_D = [100, 150, 120, 180, 140, 160, 170, 130, 190, 200, 210, 220]
ventas_E = [90,  130, 110, 170, 150, 140, 160, 150, 180, 190, 200, 210]
ventas_F = [80,  120, 100, 160, 130, 150, 140, 120, 170, 180, 190, 200]

ventas_total=np.concatenate([ventas_D, ventas_E, ventas_F])
print(ventas_total) # Unión de los tres arrays de ventas

ventas_2d=ventas_total.reshape(3, 12)
print(ventas_2d) # Ventas en 2D (3 filas

ventas_2d_transpuesta=ventas_2d.T
print(ventas_2d_transpuesta) # Transpuesta de la matriz de ventas

ventas_2d_plana=ventas_2d.flatten()
print(ventas_2d_plana) # Aplanada la matriz de ventas

ventas_2d_invertida=ventas_2d[::-1]
print(ventas_2d_invertida) # Invertida la matriz de ventas


[100 150 120 180 140 160 170 130 190 200 210 220  90 130 110 170 150 140
 160 150 180 190 200 210  80 120 100 160 130 150 140 120 170 180 190 200]
[[100 150 120 180 140 160 170 130 190 200 210 220]
 [ 90 130 110 170 150 140 160 150 180 190 200 210]
 [ 80 120 100 160 130 150 140 120 170 180 190 200]]
[[100  90  80]
 [150 130 120]
 [120 110 100]
 [180 170 160]
 [140 150 130]
 [160 140 150]
 [170 160 140]
 [130 150 120]
 [190 180 170]
 [200 190 180]
 [210 200 190]
 [220 210 200]]
[100 150 120 180 140 160 170 130 190 200 210 220  90 130 110 170 150 140
 160 150 180 190 200 210  80 120 100 160 130 150 140 120 170 180 190 200]
[[ 80 120 100 160 130 150 140 120 170 180 190 200]
 [ 90 130 110 170 150 140 160 150 180 190 200 210]
 [100 150 120 180 140 160 170 130 190 200 210 220]]


### 🧪 Ejercicio : Análisis de Ventas

In [5]:
total_venta_mes=ventas_2d.sum(axis=0)
indice_mayor=total_venta_mes.argmax()
print(f"Mes con mas ventas: {meses[indice_mayor]}")

productos = ["D", "E", "F"]
total_venta_producto=ventas_2d.sum(axis=1)
indice_min=total_venta_producto.argmin()
print(f"Producto con menos ventas: {productos[indice_min]}")

conteo_160=np.count_nonzero(ventas_2d==160)
print(f"El numero 160 aparece {conteo_160} veces en la ventas")



Mes con mas ventas: Diciembre
Producto con menos ventas: F
El numero 160 aparece 3 veces en la ventas


In [13]:
unicos=np.unique(ventas_2d)
print(f"Valores unicos: {unicos}")

valores,conteos=np.unique(ventas_2d,return_counts=True)
for val,count in zip(valores,conteos):
    print(f"El valor {val} aparece {count} veces en la matriz de ventas")

Valores unicos: [ 80  90 100 110 120 130 140 150 160 170 180 190 200 210 220]
El valor 80 aparece 1 veces en la matriz de ventas
El valor 90 aparece 1 veces en la matriz de ventas
El valor 100 aparece 2 veces en la matriz de ventas
El valor 110 aparece 1 veces en la matriz de ventas
El valor 120 aparece 3 veces en la matriz de ventas
El valor 130 aparece 3 veces en la matriz de ventas
El valor 140 aparece 3 veces en la matriz de ventas
El valor 150 aparece 4 veces en la matriz de ventas
El valor 160 aparece 3 veces en la matriz de ventas
El valor 170 aparece 3 veces en la matriz de ventas
El valor 180 aparece 3 veces en la matriz de ventas
El valor 190 aparece 3 veces en la matriz de ventas
El valor 200 aparece 3 veces en la matriz de ventas
El valor 210 aparece 2 veces en la matriz de ventas
El valor 220 aparece 1 veces en la matriz de ventas


### ✅ Nivel 6: Indexación y Slicing avanzado

In [14]:
ventas_primer_trimestre = ventas_2d[:, :3]
print("Ventas del primer trimestre:")
print(ventas_primer_trimestre)

total_ventas_mes = ventas_2d.sum(axis=0)
meses_altas_ventas = meses[total_ventas_mes > 500]
print("Meses con ventas totales mayores a 500:")
print(meses_altas_ventas)

indices_pares = [1, 3, 5, 7, 9, 11]  # Febrero, Abril, ...
ventas_meses_pares = ventas_2d[:, indices_pares]
print("Ventas en meses pares:")
print(ventas_meses_pares)


Ventas del primer trimestre:
[[100 150 120]
 [ 90 130 110]
 [ 80 120 100]]
Meses con ventas totales mayores a 500:
['Abril' 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
Ventas en meses pares:
[[150 180 160 130 200 220]
 [130 170 140 150 190 210]
 [120 160 150 120 180 200]]


In [ ]:
ventas_segundo_trimestre = ventas_2d[:, 3:6]
print(f"Ventas del segundo trimestre:{ventas_segundo_trimestre}")
meses_malos=meses[total_ventas_mes < 450]
print(f"Meses con ventas totales menores a 450:{meses_malos}")

Ventas del segundo trimestre:[[180 140 160]
 [170 150 140]
 [160 130 150]]
Meses con ventas totales menores a 450:['Enero' 'Febrero' 'Marzo' 'Mayo' 'Agosto']


In [30]:
ventas_A = np.array([100, 150, 200, 180, 170, 220, 210, 240, 250, 300, 310, 330])  # Producto A
ventas_B = np.array([90, 140, 160, 200, 230, 250, 240, 270, 290, 310, 320, 350])  # Producto B
ventas_C = np.array([110, 130, 160, 180, 210, 230, 260, 280, 300, 320, 340, 360])  # Producto C
ventas_D = np.array([80, 120, 150, 170, 200, 220, 250, 270, 290, 310, 320, 340])  # Producto D


ventas_trimestre_1 = ventas_2d[:, 0:3]  # Ventas del primer trimestre
ventas_trimestre_2 = ventas_2d[:, 3:6]  # Ventas del segundo trimestre
ventas_trimestre_3 = ventas_2d[:, 6:9]  # Ventas del tercer trimestre
ventas_trimestre_4 = ventas_2d[:, 9:12]  # Ventas del cuarto trimestre

ventas_trimestre = ventas_2d.sum(axis=1)  # Suma por productos en todo el año

ventas_trimestre_1 = ventas_2d[:, 0:3]  # Ventas de enero a marzo
ventas_trimestre_2 = ventas_2d[:, 3:6]  # Ventas de abril a junio
ventas_trimestre_3 = ventas_2d[:, 6:9]  # Ventas de julio a septiembre
ventas_trimestre_4 = ventas_2d[:, 9:12] # Ventas de octubre a diciembre



ventas_trimestre_1 = ventas_2d[:, 0:3]  # Ventas del primer trimestre
ventas_trimestre_2 = ventas_2d[:, 3:6]  # Ventas del segundo trimestre
ventas_trimestre_3 = ventas_2d[:, 6:9]  # Ventas del tercer trimestre
ventas_trimestre_4 = ventas_2d[:, 9:12] # Ventas del cuarto trimestre

print("Ventas primer trimestre:", ventas_trimestre_1)
print("Ventas segundo trimestre:", ventas_trimestre_2)

total_ventas_mes = ventas_2d.sum(axis=0)  # Suma por mes, es decir, total de ventas de todos los productos en cada mes
meses_mayores_600 = meses[total_ventas_mes > 600]  # Filtramos los meses con ventas mayores a 600
print("Meses con ventas mayores a 600:", meses_mayores_600)

ventas_totales = np.concatenate([ventas_A, ventas_B, ventas_C, ventas_D])
ventas2_2d=ventas_totales.reshape(4,12)
unicos=np.unique(ventas2_2d)
print(f"Valores unicos: {unicos}")

valores, conteos = np.unique(ventas2_2d, return_counts=True)
for val, count in zip(valores, conteos):
    print(f"El valor {val} aparece {count} veces en la matriz de ventas")



Ventas primer trimestre: [[100 150 120]
 [ 90 130 110]
 [ 80 120 100]]
Ventas segundo trimestre: [[180 140 160]
 [170 150 140]
 [160 130 150]]
Meses con ventas mayores a 600: ['Diciembre']
Valores unicos: [ 80  90 100 110 120 130 140 150 160 170 180 200 210 220 230 240 250 260
 270 280 290 300 310 320 330 340 350 360]
El valor 80 aparece 1 veces en la matriz de ventas
El valor 90 aparece 1 veces en la matriz de ventas
El valor 100 aparece 1 veces en la matriz de ventas
El valor 110 aparece 1 veces en la matriz de ventas
El valor 120 aparece 1 veces en la matriz de ventas
El valor 130 aparece 1 veces en la matriz de ventas
El valor 140 aparece 1 veces en la matriz de ventas
El valor 150 aparece 2 veces en la matriz de ventas
El valor 160 aparece 2 veces en la matriz de ventas
El valor 170 aparece 2 veces en la matriz de ventas
El valor 180 aparece 2 veces en la matriz de ventas
El valor 200 aparece 3 veces en la matriz de ventas
El valor 210 aparece 2 veces en la matriz de ventas
El val